name: SHRP CI
on:
  workflow_dispatch:
    inputs:
      pushtosf:
        description: 'set this to true if you wanna push to sf (all small)'
        required: false
env:
  MANIFEST: "https://github.com/SHRP/manifest.git -b v3_9.0"
  # Recovery Manifest URL with -b branch
  DT_LINK: "https://github.com/Iceows/shrp_android_device_huawei_potter -b android-11"
  # Your Device Tree Link
  VENDOR: "huawei"
  # Your Device's Vendor name as in used inside DT. Example: xiaomi, samsung, asus, etc.
  CODENAME: "potter"
  # Your Device's Codename as in used inside DT." Example: nikel, phoenix, ginkgo, etc.
  KERNEL_LINK: ""
  # Kernel repo link with optional -b branch. Only for building kernel from source. Ignore if using prebuilt.
  TARGET: "recoveryimage"
  # Set as recoveryimage (or bootimage if no recovery partition avaiable)
  FLAVOR: "eng"
  # eng by default, change the variable if you want userdebug
  SOURCE: "twrp"
  # Set as omni (or twrp if using v3_11.0)
  EXTRA_CMD: ""
  # For qualcomm FDE devices put git clone https://github.com/omnirom/android_vendor_qcom_opensource_commonsys --depth=1 -b android-9.0 vendor/qcom/opensource/commonsys in EXTRA CMD
  # If you want to Execute any external Command Before Compilation Starts
  TZ: "Asia/Kolkata"
  TOKEN: ${{ secrets.BOTTOKEN }}
  PUSHTOSF: ${{ github.event.inputs.pushtosf }}

jobs:
  shrpCI:
    runs-on: ubuntu-20.04

    steps:
       - name: Cleaning Up Runner
         uses: rokibhasansagar/slimhub_actions@main

       - name: Recovery Compilation
         uses: SHRP-Devices/Recovery-Compiler@release

